[build]
#target = "aarch64-linux-android"

[target.aarch64-linux-android]
linker = "aarch64-linux-android23-clang"

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi23-clang"

[target.i686-linux-android]
linker = "i686-linux-android23-clang"

[target.x86_64-linux-android]
linker = "x86_64-linux-android23-clang"

[env]
# Force CMake to use Ninja generator instead of MSBuild on Windows
CMAKE_GENERATOR = "Ninja"
