[workspace]

members = [
    "clash-android-ffi",
    "uniffi-bindgen",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
uniffi = { version = "0.31", features = ["tokio"] }
async-compat = "0.2.5"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 1
panic = "unwind"
strip = "debuginfo"

[profile.dev.package.backtrace]
opt-level = 3

[patch.crates-io]
async-compat = { git = "https://github.com/element-hq/async-compat", rev = "5a27c8b290f1f1dcfc0c4ec22c464e38528aa591" }

